"use client";

import { useState, useRef } from "react";
import { api } from "@/lib/api";
import { useApp } from "@/context/AppContext";

interface Props {
  query: string;
  responseText: string;
  onLike?: () => void;
}

export default function FeedbackBar({ query, responseText, onLike }: Props) {
  const { persona } = useApp();
  const [feedback, setFeedback] = useState<"thumbs_up" | "thumbs_down" | null>(null);
  const [showShareMenu, setShowShareMenu] = useState(false);
  const [copied, setCopied] = useState(false);
  const shareRef = useRef<HTMLDivElement>(null);

  const handleFeedback = async (type: "thumbs_up" | "thumbs_down") => {
    setFeedback(type);
    if (type === "thumbs_up" && onLike) {
      onLike();
    }
    try {
      await api.submitFeedback(query, responseText, type, persona);
    } catch (e) {
      console.error("Failed to submit feedback:", e);
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(responseText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = responseText;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
    setShowShareMenu(false);
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Vibe Analytics - Demand Sensing</title>
          <style>
            body { font-family: 'Inter', system-ui, sans-serif; padding: 40px; color: #1A1A2E; line-height: 1.6; }
            h1 { font-size: 16px; color: #3C2CDA; margin-bottom: 8px; }
            .query { background: #F0F1F5; padding: 12px; border-radius: 8px; margin-bottom: 20px; font-size: 13px; }
            .response { font-size: 13px; white-space: pre-wrap; }
            .footer { margin-top: 40px; font-size: 10px; color: #9CA3AF; border-top: 1px solid #E8E9F0; padding-top: 12px; }
          </style>
        </head>
        <body>
          <h1>Vibe Analytics - Demand Sensing Intelligence</h1>
          <div class="query"><strong>Query:</strong> ${query.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
          <div class="response">${responseText.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
          <div class="footer">Generated by Vibe Analytics | Powered by Snowflake Cortex AI</div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
    setShowShareMenu(false);
  };

  return (
    <div className="flex items-center gap-1 mt-3 pt-3 border-t border-[var(--border-color)]">
      <button
        onClick={() => handleFeedback("thumbs_up")}
        disabled={feedback !== null}
        className={`inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[11px] font-medium cursor-pointer border transition-all ${
          feedback === "thumbs_up"
            ? "bg-[var(--hex-accent)]/10 text-[var(--hex-accent)] border-[var(--hex-accent)]/30"
            : "bg-transparent text-[var(--hex-text-muted)] border-transparent hover:bg-[var(--hex-surface-2)] hover:text-[var(--hex-accent)]"
        } disabled:cursor-default`}
      >
        <span className="material-icons-outlined" style={{ fontSize: "14px" }}>thumb_up</span>
        {feedback === "thumbs_up" && <span>Liked</span>}
      </button>

      <button
        onClick={() => handleFeedback("thumbs_down")}
        disabled={feedback !== null}
        className={`inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[11px] font-medium cursor-pointer border transition-all ${
          feedback === "thumbs_down"
            ? "bg-[var(--hex-error)]/10 text-[var(--hex-error)] border-[var(--hex-error)]/30"
            : "bg-transparent text-[var(--hex-text-muted)] border-transparent hover:bg-[var(--hex-surface-2)] hover:text-[var(--hex-error)]"
        } disabled:cursor-default`}
      >
        <span className="material-icons-outlined" style={{ fontSize: "14px" }}>thumb_down</span>
      </button>

      <div className="relative" ref={shareRef}>
        <button
          onClick={() => setShowShareMenu(!showShareMenu)}
          className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[11px] font-medium cursor-pointer border border-transparent bg-transparent text-[var(--hex-text-muted)] hover:bg-[var(--hex-surface-2)] hover:text-[var(--hex-primary)] transition-all"
        >
          <span className="material-icons-outlined" style={{ fontSize: "14px" }}>share</span>
        </button>

        {showShareMenu && (
          <div className="absolute bottom-full left-0 mb-1 bg-[var(--hex-surface-1)] rounded-lg border border-[var(--border-color)] py-1 min-w-[160px] animate-scale-in z-50"
            style={{ boxShadow: "var(--shadow-md)" }}>
            <button
              onClick={handleCopy}
              className="w-full flex items-center gap-2 px-3 py-2 text-[11px] text-[var(--hex-text)] hover:bg-[var(--hex-surface-hover)] cursor-pointer border-none bg-transparent text-left transition-colors"
            >
              <span className="material-icons-outlined" style={{ fontSize: "14px" }}>content_copy</span>
              {copied ? "Copied!" : "Copy to clipboard"}
            </button>
            <button
              onClick={handleDownloadPDF}
              className="w-full flex items-center gap-2 px-3 py-2 text-[11px] text-[var(--hex-text)] hover:bg-[var(--hex-surface-hover)] cursor-pointer border-none bg-transparent text-left transition-colors"
            >
              <span className="material-icons-outlined" style={{ fontSize: "14px" }}>picture_as_pdf</span>
              Download as PDF
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
